In [1]:
pip install modin[ray]

Requirement already satisfied: modin[ray] in c:\users\jigar\anaconda3\lib\site-packages (0.15.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\jigar\anaconda3\lib\site-packages (from modin[ray]) (1.21.5)
Requirement already satisfied: packaging in c:\users\jigar\anaconda3\lib\site-packages (from modin[ray]) (21.3)
Requirement already satisfied: psutil in c:\users\jigar\anaconda3\lib\site-packages (from modin[ray]) (5.8.0)
Requirement already satisfied: pandas==1.4.3 in c:\users\jigar\anaconda3\lib\site-packages (from modin[ray]) (1.4.3)
Requirement already satisfied: fsspec in c:\users\jigar\anaconda3\lib\site-packages (from modin[ray]) (2022.3.0)
Requirement already satisfied: redis<4.0.0,>=3.5.0 in c:\users\jigar\anaconda3\lib\site-packages (from modin[ray]) (3.5.3)
Requirement already satisfied: ray[default]<1.13.0,>=1.4.0 in c:\users\jigar\anaconda3\lib\site-packages (from modin[ray]) (1.12.1)
Requirement already satisfied: protobuf<4.0.0 in c:\users\jigar\anaconda3\lib\site-packages (from modin[ray]) (3.20.1)
Requirement already satisfied: pyarrow>=4.0.1 in c:\users\jigar\anaconda3\lib\site-packages (from modin[ray]) (8.0.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jigar\anaconda3\lib\site-packages (from pandas==1.4.3->modin[ray]) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\jigar\anaconda3\lib\site-packages (from pandas==1.4.3->modin[ray]) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\jigar\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas==1.4.3->modin[ray]) (1.16.0)
Requirement already satisfied: jsonschema in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (4.4.0)
Requirement already satisfied: pyyaml in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (6.0)
Requirement already satisfied: grpcio<=1.43.0,>=1.28.1 in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.42.0)
Requirement already satisfied: attrs in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (21.4.0)
Requirement already satisfied: frozenlist in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.2.0)
Requirement already satisfied: requests in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (2.27.1)
Requirement already satisfied: click>=7.0 in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (8.0.4)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.0.3)
Requirement already satisfied: aiosignal in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.2.0)
Requirement already satisfied: virtualenv in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (20.15.1)
Requirement already satisfied: filelock in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (3.6.0)
Requirement already satisfied: opencensus in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.10.0)
Requirement already satisfied: prometheus-client<0.14.0,>=0.7.1 in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.13.1)
Requirement already satisfied: aiohttp>=3.7 in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (3.8.1)
Requirement already satisfied: smart-open in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (5.2.1)
Requirement already satisfied: colorful in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.5.4)
Requirement already satisfied: gpustat>=1.0.0b1 in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.0.0rc1)
Requirement already satisfied: aiohttp-cors in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.7.0)
Requirement already satisfied: py-spy>=0.2.0 in c:\users\jigar\anaconda3\lib\site-packages (from ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.3.12)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\jigar\anaconda3\lib\site-packages (from aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\jigar\anaconda3\lib\site-packages (from aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (5.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\jigar\anaconda3\lib\site-packages (from aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.6.3)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\jigar\anaconda3\lib\site-packages (from aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (4.0.1)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\jigar\anaconda3\lib\site-packages (from async-timeout<5.0,>=4.0.0a3->aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (4.1.1)
Requirement already satisfied: colorama in c:\users\jigar\anaconda3\lib\site-packages (from click>=7.0->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.4.4)
Requirement already satisfied: blessed>=1.17.1 in c:\users\jigar\anaconda3\lib\site-packages (from gpustat>=1.0.0b1->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.19.1)
Requirement already satisfied: nvidia-ml-py<=11.495.46,>=11.450.129 in c:\users\jigar\anaconda3\lib\site-packages (from gpustat>=1.0.0b1->ray[default]<1.13.0,>=1.4.0->modin[ray]) (11.495.46)
Requirement already satisfied: jinxed>=1.1.0 in c:\users\jigar\anaconda3\lib\site-packages (from blessed>=1.17.1->gpustat>=1.0.0b1->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.2.0)
Requirement already satisfied: wcwidth>=0.1.4 in c:\users\jigar\anaconda3\lib\site-packages (from blessed>=1.17.1->gpustat>=1.0.0b1->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.2.5)
Requirement already satisfied: ansicon in c:\users\jigar\anaconda3\lib\site-packages (from jinxed>=1.1.0->blessed>=1.17.1->gpustat>=1.0.0b1->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.89.0)
Requirement already satisfied: idna>=2.0 in c:\users\jigar\anaconda3\lib\site-packages (from yarl<2.0,>=1.0->aiohttp>=3.7->ray[default]<1.13.0,>=1.4.0->modin[ray]) (3.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\jigar\anaconda3\lib\site-packages (from jsonschema->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.18.0)
Requirement already satisfied: opencensus-context>=0.1.2 in c:\users\jigar\anaconda3\lib\site-packages (from opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.1.2)
Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in c:\users\jigar\anaconda3\lib\site-packages (from opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.25.1)
Requirement already satisfied: setuptools>=40.3.0 in c:\users\jigar\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (61.2.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in c:\users\jigar\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.53.0)
Requirement already satisfied: google-auth<2.0dev,>=1.21.1 in c:\users\jigar\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.33.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\jigar\anaconda3\lib\site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (4.7.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\jigar\anaconda3\lib\site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\jigar\anaconda3\lib\site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (4.2.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\jigar\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.21.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.4.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jigar\anaconda3\lib\site-packages (from requests->ray[default]<1.13.0,>=1.4.0->modin[ray]) (2022.5.18.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jigar\anaconda3\lib\site-packages (from requests->ray[default]<1.13.0,>=1.4.0->modin[ray]) (1.26.9)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\jigar\anaconda3\lib\site-packages (from packaging->modin[ray]) (3.0.4)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\users\jigar\anaconda3\lib\site-packages (from virtualenv->ray[default]<1.13.0,>=1.4.0->modin[ray]) (0.3.4)
Requirement already satisfied: platformdirs<3,>=2 in c:\users\jigar\anaconda3\lib\site-packages (from virtualenv->ray[default]<1.13.0,>=1.4.0->modin[ray]) (2.5.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install ray

Requirement already satisfied: ray in c:\users\jigar\anaconda3\lib\site-packages (1.12.1)
Requirement already satisfied: requests in c:\users\jigar\anaconda3\lib\site-packages (from ray) (2.27.1)
Requirement already satisfied: attrs in c:\users\jigar\anaconda3\lib\site-packages (from ray) (21.4.0)
Requirement already satisfied: pyyaml in c:\users\jigar\anaconda3\lib\site-packages (from ray) (6.0)
Requirement already satisfied: click>=7.0 in c:\users\jigar\anaconda3\lib\site-packages (from ray) (8.0.4)
Requirement already satisfied: numpy>=1.19.3 in c:\users\jigar\anaconda3\lib\site-packages (from ray) (1.21.5)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in c:\users\jigar\anaconda3\lib\site-packages (from ray) (1.0.3)
Requirement already satisfied: jsonschema in c:\users\jigar\anaconda3\lib\site-packages (from ray) (4.4.0)
Requirement already satisfied: protobuf>=3.15.3 in c:\users\jigar\anaconda3\lib\site-packages (from ray) (3.20.1)
Requirement already satisfied: frozenlist in c:\users\jigar\anaconda3\lib\site-packages (from ray) (1.2.0)
Requirement already satisfied: grpcio<=1.43.0,>=1.28.1 in c:\users\jigar\anaconda3\lib\site-packages (from ray) (1.42.0)
Requirement already satisfied: virtualenv in c:\users\jigar\anaconda3\lib\site-packages (from ray) (20.15.1)
Requirement already satisfied: aiosignal in c:\users\jigar\anaconda3\lib\site-packages (from ray) (1.2.0)
Requirement already satisfied: filelock in c:\users\jigar\anaconda3\lib\site-packages (from ray) (3.6.0)
Requirement already satisfied: colorama in c:\users\jigar\anaconda3\lib\site-packages (from click>=7.0->ray) (0.4.4)
Requirement already satisfied: six>=1.5.2 in c:\users\jigar\anaconda3\lib\site-packages (from grpcio<=1.43.0,>=1.28.1->ray) (1.16.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\jigar\anaconda3\lib\site-packages (from jsonschema->ray) (0.18.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\jigar\anaconda3\lib\site-packages (from requests->ray) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jigar\anaconda3\lib\site-packages (from requests->ray) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jigar\anaconda3\lib\site-packages (from requests->ray) (2022.5.18.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jigar\anaconda3\lib\site-packages (from requests->ray) (3.3)
Requirement already satisfied: platformdirs<3,>=2 in c:\users\jigar\anaconda3\lib\site-packages (from virtualenv->ray) (2.5.2)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\users\jigar\anaconda3\lib\site-packages (from virtualenv->ray) (0.3.4)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
import dask.dataframe as dd
import ray
ray.init()
import modin.pandas as md
import ray.data as rd

2022-07-11 17:43:12,073	INFO services.py:1456 -- View the Ray dashboard at http://127.0.0.1:8265

In [4]:
%%time
df1 = pd.read_csv('J:/ML/Internship Projects/week 6/master_data.csv')

CPU times: total: 20.8 s
Wall time: 20.9 s

In [25]:
%%time
ddf = dd.read_csv("J:/ML/Internship Projects/week 6/master_data.csv",dtype={'category_code': 'object'})

CPU times: total: 0 ns
Wall time: 7 ms

In [9]:
%%time
modin_df = md.read_csv("J:/ML/Internship Projects/week 6/master_data.csv")

CPU times: total: 2.78 s
Wall time: 18.4 s

In [10]:
%%time
ray_df = rd.read_csv("J:/ML/Internship Projects/week 6/master_data.csv")

CPU times: total: 297 ms
Wall time: 17.6 s

In [11]:
modin_df

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,cart,5773203,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
1,2019-10-01 00:00:03 UTC,cart,5773353,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
2,2019-10-01 00:00:07 UTC,cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3,2019-10-01 00:00:07 UTC,cart,5723490,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
4,2019-10-01 00:00:15 UTC,cart,5881449,1487580013522845895,NaN,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
...,...,...,...,...,...,...,...,...,...
20692835,2020-02-29 23:59:32 UTC,view,5885416,1487580005092295511,NaN,grattol,6.27,622082947,fb29909b-6ef5-4662-b4ee-288e73e5dc10
20692836,2020-02-29 23:59:39 UTC,cart,5550686,1487580008145748965,NaN,NaN,1.11,459705611,05d2add3-01f7-47ee-8364-27341673227f
20692837,2020-02-29 23:59:45 UTC,view,5850628,1602943681873052386,NaN,grattol,5.24,622090043,ab7d349f-db5d-4790-8ab1-31e5c894459d
20692838,2020-02-29 23:59:54 UTC,view,5716351,1487580010872045658,NaN,irisk,0.79,619841242,18af673b-7fb9-4202-a66d-5c855bc0fd2d
20692839,2020-02-29 23:59:59 UTC,view,5927709,1487580013950664926,NaN,de.lux,3.17,621669991,daa3c677-5360-4327-847e-d29658716b99

In [26]:
ddf.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,cart,5773203,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
1,2019-10-01 00:00:03 UTC,cart,5773353,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
2,2019-10-01 00:00:07 UTC,cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3,2019-10-01 00:00:07 UTC,cart,5723490,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
4,2019-10-01 00:00:15 UTC,cart,5881449,1487580013522845895,NaN,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9

In [12]:
df1

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,cart,5773203,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
1,2019-10-01 00:00:03 UTC,cart,5773353,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
2,2019-10-01 00:00:07 UTC,cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3,2019-10-01 00:00:07 UTC,cart,5723490,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
4,2019-10-01 00:00:15 UTC,cart,5881449,1487580013522845895,NaN,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
...,...,...,...,...,...,...,...,...,...
20692835,2020-02-29 23:59:32 UTC,view,5885416,1487580005092295511,NaN,grattol,6.27,622082947,fb29909b-6ef5-4662-b4ee-288e73e5dc10
20692836,2020-02-29 23:59:39 UTC,cart,5550686,1487580008145748965,NaN,NaN,1.11,459705611,05d2add3-01f7-47ee-8364-27341673227f
20692837,2020-02-29 23:59:45 UTC,view,5850628,1602943681873052386,NaN,grattol,5.24,622090043,ab7d349f-db5d-4790-8ab1-31e5c894459d
20692838,2020-02-29 23:59:54 UTC,view,5716351,1487580010872045658,NaN,irisk,0.79,619841242,18af673b-7fb9-4202-a66d-5c855bc0fd2d
20692839,2020-02-29 23:59:59 UTC,view,5927709,1487580013950664926,NaN,de.lux,3.17,621669991,daa3c677-5360-4327-847e-d29658716b99

In [31]:
%%writefile testutility.py
import logging
import os
import subprocess
import yaml
import datetime 
import gc
import re


################
# File Reading #
################

def read_config_file(filepath):
    with open(filepath, 'r') as stream:
        try:
            return yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            logging.error(exc)


def replacer(string, char):
    pattern = char + '{2,}'
    string = re.sub(pattern, char, string) 
    return string

def col_header_val(df,table_config):
    '''
    replace whitespaces in the column
    and standardized column names
    '''
    df.columns = df.columns.str.lower()
    df.columns = df.columns.str.replace('[^\w]','_',regex=True)
    df.columns = list(map(lambda x: x.strip('_'), list(df.columns)))
    df.columns = list(map(lambda x: replacer(x,'_'), list(df.columns)))
    expected_col = list(map(lambda x: x.lower(),  table_config['columns']))
    expected_col.sort()
    df.columns =list(map(lambda x: x.lower(), list(df.columns)))
    df = df.reindex(sorted(df.columns), axis=1)
    if len(df.columns) == len(expected_col) and list(expected_col)  == list(df.columns):
        print("column name and column length validation passed")
        return 1
    else:
        print("column name and column length validation failed")
        mismatched_columns_file = list(set(df.columns).difference(expected_col))
        print("Following File columns are not in the YAML file",mismatched_columns_file)
        missing_YAML_file = list(set(expected_col).difference(df.columns))
        print("Following YAML columns are not in the file uploaded",missing_YAML_file)
        logging.info(f'df columns: {df.columns}')
        logging.info(f'expected columns: {expected_col}')
        return 0

Overwriting testutility.py

In [13]:
%%writefile file.yaml
file_type: csv
dataset_name: df1
file_name: master_data
table_name: onlineshopping
inbound_delimiter: ","
outbound_delimiter: "|"
skip_leading_rows: 1
columns: 
    - event_time
    - product_id
    - price
    - user_id

Overwriting file.yaml

In [14]:
# Read config file
import testutility as util
config_data = util.read_config_file("file.yaml")

In [15]:
#inspecting data of config file
config_data

{'file_type': 'csv',
 'dataset_name': 'df1',
 'file_name': 'master_data',
 'table_name': 'onlineshopping',
 'inbound_delimiter': ',',
 'outbound_delimiter': '|',
 'skip_leading_rows': 1,
 'columns': ['event_time', 'product_id', 'price', 'user_id']}

In [16]:
# read the file using config file
file_type = config_data['file_type']
source_file = "J:/ML/Internship Projects/week 6/" + config_data['file_name'] + f'.{file_type}'
#print("",source_file)
df = pd.read_csv(source_file,config_data['inbound_delimiter'])
df.head()

FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,cart,5773203,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
1,2019-10-01 00:00:03 UTC,cart,5773353,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
2,2019-10-01 00:00:07 UTC,cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3,2019-10-01 00:00:07 UTC,cart,5723490,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
4,2019-10-01 00:00:15 UTC,cart,5881449,1487580013522845895,NaN,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9

In [17]:
if util.col_header_val(df,config_data)==0:
    print("validation failed")
    # write code to reject the file
else:
    print("col validation passed")
    # write the code to perform further action
    # in the pipleine

column name and column length validation failed
Following File columns are not in the YAML file ['category_code', 'event_type', 'user_session', 'brand', 'category_id']
Following YAML columns are not in the file uploaded []
validation failed

In [28]:
df1.to_csv(r'J:/ML/Internship Projects/week 6/outputfile.txt', sep = '|', index=False)

In [30]:
import gzip
with open("J:/ML/Internship Projects/week 6/outputfile.txt", 'rb') as orig_file:
    with gzip.open('J:/ML/Internship Projects/week 6/outputfile.txt.gz', 'wb') as zipped_file:
        zipped_file.writelines(orig_file)